USE PZ17_117
SELECT * FROM RepairParts
SELECT * FROM Requests
SELECT * FROM ReqStatusType
SELECT * FROM HomeTechModel
SELECT * FROM HomeTechType
SELECT * FROM Users
SELECT * FROM Comments
SELECT * FROM UserType
